[project]
name = 'Transparent-Educational-Grant-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.application-verification]
path = 'contracts/application-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.fund-disbursement]
path = 'contracts/fund-disbursement.clar'
clarity_version = 2
epoch = 2.5

[contracts.funder-registration]
path = 'contracts/funder-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.outcome-reporting]
path = 'contracts/outcome-reporting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
